[project]
name = "ci6115-food-ordering-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "colorama>=0.4.6",
    "pydantic>=2.10.4",
    "routingpy>=1.3.0",
    "ruff>=0.8.4",
    "tool>=0.8.0",
]
