from .clear_star_command import ClearStarCommand
from .set_five_star_command import SetFiveStarCommand
from .set_four_star_command import SetFourStarCommand
from .set_one_star_command import SetOneStarCommand
from .set_three_star_command import SetThreeStarCommand
from .set_two_star_command import SetTwoStarCommand
